### ISSUE TITLE
AC chronicles

### ISSUE THREAD

**Issue by fn2505** [gentlegiantJGC/AC-Explorer#5]
AC chronicles came out together with ac unity. Is there a way to access chronicles china files?

**Comment by gentlegiantJGC** [comment]
I don't know if the format is the same or not. You could try changing the folder path to that for that game. It might just crash in which case a reader would need to be specifically written for it

**Comment by fn2505** [comment]
I checked the files are .upk I think it was developed with the unreal engine. Thanks anyway.

**Comment by gentlegiantJGC** [comment]
in which case yeh no chance
